trigger:
  - main

variables:
  VSTS_TASK_DEBUG: 1
  SYSTEM_DEBUG: true

# If you have a self-hosted agent, replace 'ubuntu-latest' with your agent pool name
# If you don't have a self-hosted agent, keep 'ubuntu-latest' and request free parallelism
pool:
  name: 'Default'  # This will use your default agent pool
  # vmImage: 'ubuntu-latest'  # Uncomment this if you get free parallelism

steps:
- task: CustomTask@1
  inputs:
    requiredString: 'Test String'
    optionalNumber: '42'
    checkboxInput: true
    dropdownInput: 'option1'
    secretInput: '$(MY_SECRET)'  # This will be set in pipeline variables
  displayName: 'Run Custom Task'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'task-output.json'
    artifact: 'taskOutput'
    publishLocation: 'pipeline'
  displayName: 'Publish Task Output'

- script: |
    echo "Task completed. Check the logs above for details."
  displayName: 'Verify Task Completion' 