version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: "~/Documents/projects/interviews/SeaLights - Demos/"
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: surge-app-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: surge-app-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      # - run: npm run build
      - deploy:
          command: ./node_modules/.bin/surge --project ./demos/04-integration-circleci/
          # SURGE_LOGIN & SURGE_TOKEN were added to circleCi's project settings
workflows:
    build-and-test:
      jobs:
        - build-and-test